name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "staging", "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2

    - if: matrix.os == 'ubuntu-latest'
      name: Install dependencies
      run: sudo apt-get install libsoup-3.0-dev libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
