name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "staging", "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2

    - if: matrix.os == 'ubuntu-latest'
      name: Install Ubuntu dependencies
      run: sudo apt-get install -y libsoup-3.0-dev libwebkit2gtk-4.1-dev javascriptcoregtk-4.1 build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

    - if: matrix.os == 'windows-latest'
      name: Install Windows dependencies
      run: |
        choco install postgresql --version=15
        echo "::add-path::C:\Program Files\PostgreSQL\15\bin"


    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
